# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynam
use_frameworks!
pod 'Alamofire', '~> 4.8'
pod 'PINRemoteImage', '3.0.0-beta.13'
pod 'SwiftyJSON'
end
