# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

PROJECT_NAME = 'iOSPractice'
TEST_TARGET = 'iOSPracticeTests'

target PROJECT_NAME do
  # Comment the next line if you're not using Swift and don't want to use dynam
use_frameworks!
pod 'Alamofire', '~> 4.8'
pod 'PINRemoteImage', '3.0.0-beta.13'

target TEST_TARGET do
  project PROJECT_NAME
  inherit! :search_paths
  pod 'EarlGrey'
end

end